service: signLambda
provider:
  name: aws
  runtime: nodejs6.10

functions:
  list:
    handler: handler.list
    events:
      - http:
          path: media
          method: get
          cors: true
  sign:
    handler: handler.sign
    events:
      - http:
          path: media
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Cache-Control
              - X-Requested-With